### ISSUE TITLE
User Story 2: Criar setores 

### ISSUE THREAD

**Issue by JoaoVitorPereiraUFU** [ronaldoapf/PDS1#8]
## Como adminstrador do aplicativo de setores desejo criar um mapa de setores para Monte Carmelo, com objetivo de agrupar as regiões da cidade.

> Com a criação do mapa de setores a prefeitura terá grandes benefícios no que diz respeito a organização administrativa da cidade. Vale ressaltar que o administrador tem o papel de atualizar os setores e manter a base de dados da aplicação.

Critérios de Aceitação:
- Identificar regiões semelhantes
- Criar base de dados
- Criar setores já existentes na cidade
- Criar novos setores de acordo com crescimento da cidade e povoamento da base de dados

### Tarefas:
- [ ] Utilizar api do OpenStreetMap para coletar dados e criar uma base de dados (8 dias)
- [ ] Implementar o banco de dados a partir da base obtida pela API OpenStreetMap (3 dias)
- [ ] Cruzar as informações no banco de dados para montar a setorização (5 dias)
- [ ] Implementar uma interface para o usuário, prefeitura e administrador (1 dia)
- [ ] Implementar interface para criação de setores (1 dia)

### INVEST
- Independent: A estória é independente devido ao fato que não será necessário implementar outra estória para utilizá la, e pode ser implementada a qualquer momento.

- Negotiable  : A estória é negociável, devido ao fato de que seu objetivo é montar um mapa de setores baseado na coleta de informações via OpenStreetMap e IBGE, logo caso seja necessário efetuar alguma mudança com relação ao tipo de informação que sera mostrada ou exibida por setores, esta vai se adaptar.

- Valuable : O grande valor desta estória é que ela é um dos pilares para o funcionamento do sistema, a partir dela é possível executar todas as funcionalidades propostas no sistema.

- Estimable: A user story levaria 21 dias para ser feita de acordo com a estimativa feita pelo grupo. Levando em consideração que os critérios de aceitação e as tarefas a serem realizadas são de extrema importância para o pontapé inicial do sistema.

- Testable: 

### Hierarquia

- Epic: Criar setores
- Feature : Coleta de dados para criação dos setores
- User storys:  
     - Buscar dados do IBGE.
     - Buscar dados do OpenStreetMap.
 
## 3 C's

- Cartão:
Título: Criar um mapa de setores para a cidade de Monte Carmelo.
Ator: Administrador do aplicativo
Objetivo: Agrupar as regiões semelhantes, com o intuito de criar setores.
Benefícios: Usar livremente o mapa de setores para identificar alguma região ou setor, saber aonde o usuário está realmente localizado no setor.

- Conversa: Formulários para identificar se há mesmo novos setores ou se o mesmo já está cadastrado na base de dados.

- Confirmação:
